name: autobackup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          WA_AUTH_TOKEN: ${{ secrets.WA_AUTH_TOKEN }}
          WA_APP_KEY: ${{ secrets.WA_APP_KEY }}
        run: npm run autobackup
